### ISSUE TITLE
Bash Lib is opensourced

### ISSUE THREAD

**Issue by hughsaunders** [cyberark/bash-lib#2]
As a developer I want bash-lib to be open source so that I can use it in open source projects. 

ToDo:
- [x] As an operator I want to automatically scan this repo for exposed secrets using [gitleaks](https://github.com/zricethezav/gitleaks) or similar so that it does not become a source of leaks.
- [x] Add license
- [x] Add CONTRIBUTING.md
- [x] review logs

**Comment by izgeri** [comment]
Done! 💥
